### ISSUE TITLE
Implement tag editing

### ISSUE THREAD

**Issue by NilsEnevoldsen** [gmac/menagerie#12]
AFAICT, if a tag needs to be changed (to fix capitalization or something), it must be individually changed on all cards. It would be good to be able to bulk-delete and bulk-edit tags.

**Comment by gmac** [comment]
Yerp, theres a hidden area started in the admin for that. Haven't linked it in the nav yet

**Comment by gmac** [comment]
This is done, though requires a Scryfall account so is still behind the beta wall.
