### ISSUE TITLE
Tweak fonts

### ISSUE THREAD

**Issue by NilsEnevoldsen** [gmac/menagerie#14]
On the results page (e.g. https://tagger.scryfall.com/search?type=tag&q=tutor) the name of the card is lighter weight (200 vs 400) and smaller size (14 vs 16) than the illustration credit and copyright. I think the name of the card should be more prominent, not less.

**Comment by NilsEnevoldsen** [comment]
Fixed?

**Comment by gmac** [comment]
fixed.
