### ISSUE TITLE
Not obvious what dispute resolution buttons do for admin

### ISSUE THREAD

**Issue by NilsEnevoldsen** [gmac/menagerie#15]
Not obvious whether the "accept" button accepts the _tag_ or the _dispute_. (It accepts the tag.)

**Comment by gmac** [comment]
A dispute is really just a flagging that surfaces the tag to the top of the admin list. It doesn't really do anything besides draw attention to the tag. Otherwise, a the tag is approved or rejected as normal. Accepted tags will clear the dispute status.

**Comment by gmac** [comment]
This entire UI has been changed.
