### ISSUE TITLE
Overloading tags

### ISSUE THREAD

**Issue by NilsEnevoldsen** [gmac/menagerie#16]
Currently card-tags and art-tags can be overloaded. This could potentially be an issue if somebody wanted to find, say cards that were sac outlets (cards that could plausibly be tagged `aristocrat`, e.g. Teysa, Orzhov Scion), but not art that features aristocrats (e.g. Blood Baron of Vizkopa). I don't have a specific suggestion.

**Comment by april** [comment]
Another example is burn, both cards that do direct damage and a card where someone might be burnt.

**Comment by april** [comment]
Another one I ran into today was `ritual`, which covers both Dark Ritual (card) and Hymn to Tourach (art).

**Comment by april** [comment]
Also, I have cards like Hanna, Ship's Navigator (`hanna` as card) and Opt (`hanna` as art).

**Comment by gmac** [comment]
So basically – tag types.

**Comment by gmac** [comment]
Tag types are now implemented. Tags are unique to `name/type` tuples.
