### ISSUE TITLE
Allow certain tags to be bannable

### ISSUE THREAD

**Issue by april** [gmac/menagerie#21]
With a description that pops up as to why they're disallowed.

For example – and this may not be a perfect one – I recently disapproved (or maybe just saw) a tag called "burning". In this case, it would be suggest one of two options:

* Fire  (Artwork Tag of cards that depict fire or things burning)
* Burn (Card Tag of cards that do direct damage to creatures or players)

**Comment by gmac** [comment]
Let's focus this discussion within #17
