### ISSUE TITLE
Reduce captchas that need to be solved

### ISSUE THREAD

**Issue by april** [gmac/menagerie#22]
A couple changes would be hugely helpful:

* Administrators should be immune to captchas
* Regular users should only have to solve a captcha initially and then perhaps every X tags, where X is a reasonable number like 10 or something.

**Comment by gmac** [comment]
behavior is updated... users will be cookied for 15 minutes after submitting a valid captcha, and their cookie will be refreshed upon each submission while valid. So in effect, a user is only asked for a captcha after 15 minutes of inactivity. Still no special treatment for admins at this point, but I feel a lot less bad about that with the burden of captcha reduced so much now.

**Comment by april** [comment]
Next alcoholic (or virgin alcoholic) beverage is on me!
