### ISSUE TITLE
Warn when tagging creatures with their creature type

### ISSUE THREAD

**Issue by april** [gmac/menagerie#24]
`vampire` as a tag should, according to the current rules, only tag cards that depict vampires but are not creature type vampire. Menagerie should warn/forbid tagging in this manner, since it's a really just a search query.

If/when it gets integrated into Scryfall, I could see a complete query being like:
`type:vampire depicts:vampire`

**Comment by gmac** [comment]
That's fair, though it is an awkward line to draw given the same could be said about card title... at which time a tag like "sphere" could have interesting tagging but not include "sphere of resistance". I guess I could see this as a warning, but not a hard blacklist.

**Comment by april** [comment]
I think tagging things in the title is perfectly fine – titles are really just flavor for the most part, except for Legendary creatures. And there are cards like Gravity Sphere which have no actual sphere in the art.

I don't think you should be able to tag anything that's in the type line at all. A card with Creature – Bear will *always* have a bear in it. It's not super interesting for them to be tagged that way, and clogs up the actually interesting results of non-bears that are tagged with bear.

**Comment by gmac** [comment]
Closing this as a `wontfix`. To be honest, I don't see any future where this UGC data interacts directly with card data. Tagger's mandate is specifically UGC, and it's rather lame if you can't tag a creature type of `bear` as such to include it in the Bear page. Fastfoward to the hypothetical future where Tagger does submit some UGC taxonomy to Scryfall search, at which time the preferred way to see all bears identified through hard data and UGC data would be to search `type:bear art:bear` (assuming `art` is an operator for UGC artwork tags).
