### ISSUE TITLE
Confused about what exactly I'm looking at on the admin page

### ISSUE THREAD

**Issue by NilsEnevoldsen** [gmac/menagerie#30]
For example:

Angelic Wall had four pending tags: angel, cloud, giant, plains. On the admin page, I saw Angelic Wall with one tag to approve: angel. I approved that tag. Why were cloud, giant, and plains not shown on the admin page?

**Comment by gmac** [comment]
Probably due to pagination... which doesn't play nicely with that kind of grouped display. That admin screen is going to evolve into something different anyway
