### ISSUE TITLE
Discussion: card-to-card tagging/connections

### ISSUE THREAD

**Issue by NilsEnevoldsen** [gmac/menagerie#9]
* What should card-to-card connections look like?

**Comment by gmac** [comment]
Proposal:

![screen shot 2017-11-02 at 10 12 53 am](https://user-images.githubusercontent.com/727224/32330450-8d424aae-bfb6-11e7-9fda-99961c752aac.png)

Label options for card connections:

![screen shot 2017-11-02 at 10 13 05 am](https://user-images.githubusercontent.com/727224/32330456-90bacbf2-bfb6-11e7-920b-0df14d1fc58a.png)

Thoughts?

**Comment by NilsEnevoldsen** [comment]
I like. 

I would add prepositions so it's clear which way the relationship runs:

 - similar to
 - better than
 - worse than
 - related to

I would add:

 - in a cycle with
 - references / referenced by
 - colorshifted

with "related to" being the catch-all.

Unrelated thought: Scryfall should separately add basic land cycles/themes. I don't think these need to be user-curated. The Esper basic land cycle, the artist cycles from C16, etc.

**Comment by NilsEnevoldsen** [comment]
I like the tag type on the left, too.

**Comment by gmac** [comment]
Cool. How would you order those eight in terms of common use cases? (putting most common at the top and least commonly used at the bottom)

**Comment by NilsEnevoldsen** [comment]
Spitballing:
 - similar to
 - in a cycle with
 - better than
 - worse than
 - references
 - referenced by
 - colorshifted
 - related to

In which I have put "related to" at the bottom because it's a catch-all, not because it's necessarily least common.

**Comment by gmac** [comment]
Also... these are unfortunately not all bi-directional descriptors; many are uni-directional. That means creating a connection will have to establish a relationship in each direction for the cards. Let's clarify what those are:

* User tags "similar to" (same relation in both directions):
  - `a similar to b`
  - `b similar to a`

* User tags "better/worse" than (creates a relation in each direction):
  - `a better than b`
  - `b worse than a`

* User tags "related to" (actually... what does this really mean? Do we need this one?):
  - `a related to b`
  - `b related to a`

* User tags "in a cycle with" (same relation in both directions):
  - `a in a cycle with b`
  - `b in a cycle with a`

* User tags "references/by" (creates a relation in each direction):
  - `a references b`
  - `b referenced by a`

* User tags "colorshifted" (same relation in both directions...?):
  - `a colorshifted b`
  - `b colorshifted a`

**Comment by NilsEnevoldsen** [comment]
Correct in all cases.

I was thinking that, for instance, Dragonlord Dromoka could be "related to" Dromoka's Command, or Phage could be "related to" Akroma.

**Comment by gmac** [comment]
Talking with Chuck about this, I think we're going to drop `in a cycle` as a relationship. Trying to do, say, fetchlands is going to create an unwieldy number of connections... that's actually a place where a tag would make a lot more sense, given that you end up with N connections rather than N log N.

**Comment by april** [comment]
Something like half the cards in a set are `in a cycle`, the tag would be basically insane.

I would like to propose one that I think shouldn't be too controversial, Familial Relationships. This would be exposed only on Legendary cards. So, for example, Volrath would have Sidar Kondo as `Father`, and Sidar Kondo would have Volrath as `Son`.

**Comment by NilsEnevoldsen** [comment]
I realize how many connections cycles would create. But they're an important part of design. That's why they're so common. I believe this information should be accessible - even surfaced - somehow.

**Comment by gmac** [comment]
I don't disagree, there are just more efficient approaches to structuring
that kind of relationship

**Comment by gmac** [comment]
This is up and running https://tagger.scryfall.com/tagging/time-walk-amy-weber-3972
